#use_frameworks!
platform :ios, '8.0'

target 'GTThirdPlatformManager_Example' do
  
   pod 'PTTestKit', :path => '../../PTTestKit'



  pod 'GTThirdPlatformManager', :path => '../'
  pod 'GTThirdPlatformManager/AlipayManager', :path => '../'
  pod 'GTThirdPlatformManager/TencentManager', :path => '../'
  pod 'GTThirdPlatformManager/WeiboManager', :path => '../'
  pod 'GTThirdPlatformManager/WXManager', :path => '../'
  pod 'GTThirdPlatformManager/DingTalkManager', :path => '../'

end
